# -*- coding: utf-8 -*-
"""homework2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q604lzI1Jq6fpIvV-IRLZ51OlVbzx22x
"""

import random
import math
import urllib.request
import os
import zipfile
import io

# ─── Core Functions

def tokenize(text):
    return text.lower().split()

def build_vocab(dataset):
    vocab = set()
    for text, label in dataset:
        tokens = tokenize(text)
        vocab.update(tokens)
    return vocab

def build_word_counts(dataset):
    vocab = build_vocab(dataset)
    total_words  = {"spam": 0, "normal": 0}
    class_counts = {"spam": 0, "normal": 0}
    word_counts  = {
        "spam":   {word: 0 for word in vocab},
        "normal": {word: 0 for word in vocab}
    }
    for text, label in dataset:
        tokens = tokenize(text)
        class_counts[label] += 1
        total_words[label]  += len(tokens)
        for token in tokens:
            word_counts[label][token] += 1
    #  zero counts to 0.1
    for label in word_counts:
        for word in word_counts[label]:
            if word_counts[label][word] == 0:
                word_counts[label][word] = 0.1
    return total_words, class_counts, word_counts

def compute_likelihoods(word_counts, total_words, vocab):
    likelihoods = {"spam": {}, "normal": {}}
    for label in ["spam", "normal"]:
        for word in vocab:
            likelihoods[label][word] = word_counts[label][word] / total_words[label]
    return likelihoods

def compute_priors(class_counts):
    total_docs = sum(class_counts.values())
    priors = {}
    for label, count in class_counts.items():
        priors[label] = count / total_docs
    return priors


def score(text, label, priors, likelihoods, total_words):
    tokens = tokenize(text)
    result = math.log(priors[label])
    for token in tokens:
        if token in likelihoods[label]:
            result += math.log(likelihoods[label][token])
        else:
            result += math.log(0.1 / total_words[label])  # same manual fallback
    return result

def predict(text):
    return max(["spam", "normal"], key=lambda label: score(text, label, priors, likelihoods, total_words))


# ─── Train/Test Split
def train_test_split(dataset, test_ratio=0.2, seed=42):
    data = dataset[:]
    random.seed(seed)
    random.shuffle(data)
    split = int(len(data) * (1 - test_ratio))
    return data[:split], data[split:]


# ─── Evaluation

def evaluate(test_set, priors, likelihoods, total_words):
    tp = fp = fn = tn = 0
    for text, true_label in test_set:
        predicted = predict(text)
        if predicted == "spam" and true_label == "spam":
            tp += 1
        elif predicted == "spam" and true_label == "normal":
            fp += 1
        elif predicted == "normal" and true_label == "spam":
            fn += 1
        else:
            tn += 1

    # Actual counts from test set
    actual_spam   = sum(1 for _, label in test_set if label == "spam")
    actual_normal = sum(1 for _, label in test_set if label == "normal")

    # Predicted counts
    predicted_spam   = sum(1 for text, _ in test_set if predict(text) == "spam")
    predicted_normal = sum(1 for text, _ in test_set if predict(text) == "normal")

    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall    = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    f1        = (2 * precision * recall / (precision + recall)
                 if (precision + recall) > 0 else 0.0)

    print(f"Total test samples : {len(test_set)}")
    print(f"")
    print(f"Actual Distribution:")
    print(f"  Spam   : {actual_spam}")
    print(f"  Normal : {actual_normal}")
    print(f"")
    print(f"Predicted Distribution:")
    print(f"  Spam   : {predicted_spam}")
    print(f"  Normal : {predicted_normal}")
    print(f"")
    print(f"TP={tp}, FP={fp}, FN={fn}, TN={tn}")
    print(f"")
    print(f"Precision : {precision:.4f}")
    print(f"Recall    : {recall:.4f}")
    print(f"F1 Score  : {f1:.4f}")




print("\nStep 1: Load Dataset      → done on FULL dataset (just loading)")
print("Step 2: Tokenization      → done on FULL dataset (just display)")
print("Step 3: Train/Test Split  → done on FULL dataset → splits into train/test")
print("Step 4: Vocabulary        → only on TRAIN set ")
print("Step 5: Word Counts       → only on TRAIN set ")
print("Step 6: Priors            → only on TRAIN set ")
print("Step 7: Likelihoods       → only on TRAIN set ")
print("Step 8: Evaluation        → only on TEST set \n ")
# ─── Step 1: Load Dataset (auto-download if missing) ─────────────────────────



def load_sms_dataset(filepath="SMSSpamCollection"):
    if not os.path.exists(filepath):
        print("Dataset not found locally. Downloading...")
        url = "https://archive.ics.uci.edu/ml/machine-learning-databases/00228/smsspamcollection.zip"
        with urllib.request.urlopen(url) as response:
            zip_data = response.read()
        with zipfile.ZipFile(io.BytesIO(zip_data)) as z:
            with z.open("SMSSpamCollection") as f:
                content = f.read().decode("utf-8")
        with open(filepath, "w", encoding="utf-8") as out:
            out.write(content)
        print("Download complete. Saved as 'SMSSpamCollection'.")
    else:
        print("Dataset found locally.")

    dataset = []
    with open(filepath, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            parts = line.split("\t", 1)
            label_raw, text = parts[0], parts[1]
            label = "normal" if label_raw == "ham" else "spam"
            dataset.append((text, label))
    return dataset

print("=== Step 1: Load Dataset ===")
dataset = load_sms_dataset()
print(f"Total samples: {len(dataset)}")
print(f"First 3 samples:")
for text, label in dataset[:3]:
    print(f"  {label:6} | '{text[:60]}...'")


# Step 3: Split first
print("\n=== Step 3: Train/Test Split ===")
train_set, test_set = train_test_split(dataset)
print(f"Training samples : {len(train_set)}")
print(f"Test samples     : {len(test_set)}")

# Step 2: Tokenize only AFTER split, on train only
print("\n=== Step 3: Tokenization on only first 70 rows due to large datset ===")
for text, label in train_set[:70]:
    print(f"{label:6} | '{text[:40]}' -> {tokenize(text)}")




# ─── Step 4: Vocabulary


print("\n=== Step 4: Vocabulary ===")
vocab = build_vocab(train_set)
print(f"Vocabulary: {sorted(vocab)}")
print(f"Vocabulary size: {len(vocab)}")





# ─── Step 5: Word Counts (on train_set only)

print("\n=== Step 5: Word Counts ===")
total_words, class_counts, word_counts = build_word_counts(train_set)
print("total_words :", total_words)
print("class_counts:", class_counts)


# ─── Step 6: Priors

print("\n=== Step 6: Priors ===")
priors = compute_priors(class_counts)
for label, value in priors.items():
    print(f"  {label}: {value:.3f}")

# ─── Step 7: Likelihoods

print("\n=== Step 7: Likelihoods ===")
vocab = build_vocab(train_set)
likelihoods = compute_likelihoods(word_counts, total_words, vocab)
print(f"Likelihoods computed for {len(likelihoods['spam'])} words")



# ─── Step 9: Evaluate on Test Set

print("\n=== Step 9: Evaluation ===")
evaluate(test_set, priors, likelihoods, total_words)

"""# New section"""